import "./globals.css";
import Providers from "./providers.jsx";

export const metadata = {
  title: "Portfolio | Rifky Ari ",
  description: "Generated by create next app",
};

export default function RootLayout({ children = null }) {
  return (
    <>
      <html>
        <body>
          <Providers>{children}</Providers>
        </body>
      </html>
    </>
  );
}